index.html
There's bigger fishes to fry I am sure.
I really thought https://shadow-cljs.github.io/ was the homepage before today. 🤣
Not sure what the long term plan is (for example we can just redirect it), but at least a link on that page for people to not make the same mistake as I.
=> homepage link

docs/UsersGuide.html, docs/editor-integration.adoc
The docs were requesting help in the Emacs/CIDER section, I've responded by adding comprehensive instructions for Emacs/CIDER users.
I've used AsciiDoc example blocks in places, which aren't used afaik in the docs up until now. I'm happy to amend if you have style preferences against these.
For user convenience I've regenerated `UserGuide.html`, which is part of this PR (but doesn't have to be).
=> add emacs/cider documentation

docs/editor-integration.adoc
* Use `ctrl+alt+c` instead of `ctrl+alt+v` because `ctrl+alt+v` is no
longer used on latest calva version.
* Remove `calva.openREPLTerminal: ctrl+alt+v z` keybind.
* Change `calva.toggleCLJCSession` keybind from `ctrl+alt+v alt+c` to `ctrl+alt+c ctrl+alt+t`.
cf. https://github.com/BetterThanTomorrow/calva/blob/master/package.json
=>  Update Calva keybinds for latest calva version

docs/editor-integration.adoc
Simplify the section of CIDER. 
CIDER now has built-in support to start with a single command with shadow-cljs.
=> Update CIDER section

.devcontainer.json, Dockerfile, README.md, docs/UsersGuide.html, docs/repl-troubleshoot.adoc
I found a typo that I wanted to fix but then realised I needed to have Ruby, Bundler and Make. I think that providing a dockerised development environment will facilitate and encourage external contribution.
I did this in three separate commits:
- The first one defines the Dockerfile
- The second one is VS Code specific
- The third one is the actual typo fix
If you prefer to keep Docker away, we can just ignore the first two commits.
=> Fix typo + create a Dockerfile to facilitate development and contribution

docs/UsersGuide.html, docs/editor-integration.adoc
The CIDER variable name for build name is `cider-shadow-default-options`, not `cider-shadow-cljs-default-options`.
Here's a link to the place in CIDER where it's defined (permalink to current master):
https://github.com/clojure-emacs/cider/blob/cc52e696e3647229f4075c90f267c33d0940757f/cider.el#L711
=> Fix CIDER variable name for build name

docs/UsersGuide.html, docs/editor-integration.adoc
The correct name for the Emacs dir locals file is `.dir-locals.el`, not `dir-local.el`.
See https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html
=> Fix Emacs dir-locals filename

docs/target-react-native.adoc
Since the steps in the main section are applicable to the plain
react-native setup and since only the Expo section was present,
decided to add this section with the link to the sample repo.
I'm not 100% sure about the way the "plain" `react-native` and Expo `react-native` should be differentiated and described. But figured to create this PR to at least start the discussion. 
What do you think? 
As for the repo linked, it does work and the steps are applicable.
I mainly wanted it in the documentation, since it's relevant and can be run by just following the README.
Thanks
=> Added documentation about the plain react-native

docs/editor-integration.adoc
Change link to current Calva extension marketplace page (was linked to legacy). Change command for connecting to new command name (also seemed to be legacy).
=> Update Calva editor integration info

docs/usage.adoc
A simple typo fix. Spotted it while reading the documentation.
=> typo fix for 3.3. Running Clojure Code section

docs/maven-publish.adoc
The publishing section references deps.cljs which I wasn't aware of. I think it would be useful to include a link that provides more context for deps.cljs.
=> Added link to cljs's foreign dep reference.

docs/UsersGuide.html, docs/build-config.adoc
I've added `:bare-minimum`, `:es2018`, and `:es2019`, and `:es2020`. The note for `:es8` listed object spread syntax, but that is actually an `:es2018` feature, so I've moved it.
I don't know what `:es-next-in` is for, so I haven't included it.
=> Document additional :output-feature-set options

docs/UsersGuide.html, docs/release.adoc
I was curious about this, so figure someone (maybe my future self) will want to know this too.
=> Make clear that build reports are not affected by already running watches

docs/release.adoc
Addresses some unclear sentences on when to use `^clj` and `^js`
annotations. Since these are unclear, it's possible my revisions introduced an error. Even with that possibility, I thought opening a PR would be faster than writing an issue.
=> Fix unclear sentences in JavaScript Integration chapter.

docs/UsersGuide.adoc
The push-state handler will only respond to HTTP requests with "Accept: text/html" headers. Mentioning this in the docs can be helpful if someone is wondering why curl or such tools don't see the same response.
Not sure if this is the best place or if this is confusing detail for some readers, but I think this will be useful to mention.
=> Mention push-state handler checks Accept header

docs/editor-integration.adoc
Added an alternative `.dir-locals.el` setup when watching several builds.
Also, added a link to the Cider docs about ClojureScript and shadow-cljs configuration options.
=> docs: Emacs setup with .dir-locals.el

docs/UsersGuide.html, docs/target-npm-module.adoc
Link was broken...
ps. The `make docker-build` is pulling `asciidoctor:latest`, which today seemed to be `asciidoctor 2.0.17`. There were some major changes in the output HTML with v2. So I just used the gem version `1.5.6.1` to generate this.
=> fix :node-library link

docs/js-deps.adoc
I believe the example uses `$export` instead of `$default` by mistake.
=> Fix default export example

docs/target-browser-test.adoc
Without it, failing tests disappear when the tests are hot reloaded for the first time
=> Add `:dev/always` to custom `runner-ns` example

docs/build-config.adoc, docs/target-react-native.adoc
In react native all (including transitive) dependents must be reloaded, for change to take effect. For specific cases check out [this repository](https://github.com/lbrdnk/repro__shadow-cljs__reload).
=> Mention use of `:reload-strategy`

docs/release.adoc
Google Closure compiler has deprecated code stripping and made the APIs non-public. In fact, shadow-cljs has been ignoring the keys documented in the "Code Stripping" section. Hence remove the documentation.
=> Remove code stripping documentation

README.md, docs/UsersGuide.html, docs/js-deps.adoc
This PR: 
- adds a link to the VS code remote containers extension to avoid ambiguity and fixes a typo in Readme.
- fixes the example of the Babel config file in docs (correct usage of the plugin is presented here https://babeljs.io/docs/babel-plugin-transform-react-jsx#with-a-configuration-file-recommended) and adds a link to the page with more info about configuration files.
=> Update readme and babel refs

docs/target-browser.adoc
Hi,
just went trough the exercise of writing a script to rewrite my html file to include the main module's hash, only to then find the hooks mechanism and a pre-written hook that does exactly what I need :star_struck: I think having this info here might be helpful to others.
Cheers,
Simon
=> Expand on `:module-hash-names` integration

docs/js-deps.adoc
It seemed to be copy-pasta from above _`:shadow` vs `:closure`_ paragraph
=> fix :entry-keys config explanation
